project:
  type: website
  output-dir: docs

website:
  title: "PSY6422 Quarto Website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: secondpage.qmd
        text: Page 3

format:
  html:
    theme:
    - cosmo
    css: styles.css
    toc: true



